// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	RoomID        int32 `json:"room_id"`
	MaxGuests     int32 `json:"max_guests"`
	Balcony       bool  `json:"balcony"`
	Fridge        bool  `json:"fridge"`
	IndoorPool    bool  `json:"indoor_pool"`
	GamingConsole bool  `json:"gaming_console"`
}

type RoomAvailability struct {
	RoomID      int32       `json:"room_id"`
	Date        pgtype.Date `json:"date"`
	IsAvailable bool        `json:"is_available"`
	NightRate   int32       `json:"night_rate"`
}
