// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	RoomID        int32       `json:"room_id"`
	MaxGuests     pgtype.Int4 `json:"max_guests"`
	Balcony       pgtype.Bool `json:"balcony"`
	Fridge        pgtype.Bool `json:"fridge"`
	IndoorPool    pgtype.Bool `json:"indoor_pool"`
	GamingConsole pgtype.Bool `json:"gaming_console"`
}

type RoomAvailability struct {
	RoomID      pgtype.Int4    `json:"room_id"`
	Date        pgtype.Date    `json:"date"`
	IsAvailable pgtype.Bool    `json:"is_available"`
	NightRate   pgtype.Numeric `json:"night_rate"`
}
